tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: error_code
            field:
              type: text
              display: 'Error Code'
          -
            handle: short_message
            field:
              type: text
              display: 'Short Message'
          -
            handle: descriptive_message
            field:
              type: textarea
              display: 'Descriptive Message'
          -
            import: button
